// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Contacts',
      link: {type: 'doc', id: 'components/contacts/index'},
      items: [
        'components/contacts/contact-list',
        'components/contacts/contact-actions',
        'components/contacts/contact-profile',
      ],
    },
     {
      type: 'category',
      label: 'Households',
      link: {type: 'doc', id: 'components/households/index'},
      items: [
        'components/households/household-list',
        'components/households/household-actions',
        'components/households/entity-management',
      ],
    },
      'components/opportunities',
      'components/tasks',
      'components/workflows',
       'components/meetings',
   
  
  
   
  ]
};

export default sidebars;
