// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Get Started',
      link: {type: 'doc', id: 'components/about/index'},
      items: [
        'components/about/platform-overview',
        'components/about/getting-started',
        'components/about/home',
        'components/about/navigation',
        'components/about/user-profile',
        'components/about/settings',
        'components/about/notifications',
      ],
    },
    {
      type: 'category',
      label: 'Client Management',
      link: {
        type: 'generated-index',
        title: 'Client Management',
        description:
          "Manage your relationships effectively with a comprehensive view of contacts and households. Learn how to customize client data with unique fields, build dynamic lists for servicing, and maintain compliance records.",
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [
        {
          type: 'category',
          label: 'Contacts',
          link: {type: 'doc', id: 'components/contacts/index'},
          items: [
            'components/contacts/contact-list',
            'components/contacts/contact-actions',
            'components/contacts/contact-profile',
          ],
        },
        {
          type: 'category',
          label: 'Households',
          link: {type: 'doc', id: 'components/households/index'},
          items: [
            'components/households/household-list',
            'components/households/household-actions',
            'components/households/entity-management',
            'components/households/activities',
            {
              type: 'category',
              label: 'Financial Data',
              items: [
                'components/households/financials',
                'components/institutions',

              ],
            },
            'components/households/planning',
            'components/households/documents',
          ],
        },
        'components/custom-views',
        

      ],
    },
      'components/opportunities',
    {
      type: 'category',
      label: 'Productivity Tools',
      link: {
        type: 'generated-index',
        title: 'Productivity Tools',
        description:
          "Supercharge your daily efficiency using the AI Assistant (SuperMode) and integrated task management. Discover how to automate routine actions, manage your calendar with booking links, and keep detailed notes.",
        keywords: ['tools'],
        image: '/img/docusaurus.png',
      },
      items: [
        'components/tasks',
        'components/emails',
        {
          type: 'category',
          label: 'Meetings',
          link: {type: 'doc', id: 'components/meetings/index'},
          items: [
            'components/meetings/meetings-list',
            'components/meetings/schedule-meetings',
            'components/meetings/executing-meetings',
            'components/meetings/manage-meetings',
          ],
        },
         'components/notes',
      ]
    },
    {
      type: 'category',
      label: 'Financial Records',
      link: {type: 'doc', id: 'components/financial-records/index'},
      items: [
        'components/financial-records/assets',
        'components/financial-records/liabilities',
        'components/financial-records/investments',
        'components/financial-records/pensions',
      ]
    },
   {
      type: 'category',
      label: 'Operations & Process Automation',
      link: {
        type: 'generated-index',
        title: 'Operations & Process Automation',
        description:
          "Standardize your service delivery and eliminate manual errors. Learn to build automated workflows for complex processes like onboarding and use custom forms to gather structured client data.",
        keywords: ['automation'],
        image: '/img/docusaurus.png',
      },
      items: [
        'components/workflows',
        'components/forms',
        'components/my-scenarios',
      ]
    },
    {
      type: 'category',
      label: 'My Practice',
      link: {
        type: 'generated-index',
        title: 'My Practice',
        description:
          "Configure the backend of your firm. Manage team permissions, set up billing products, white-label the platform with your branding, and define organization-wide settings.",
        keywords: ['practice'],
        image: '/img/docusaurus.png',
      },
      items: [
         'components/my-practice/products',
         'components/my-practice/manage-team',
         'components/my-practice/service-models',
          'components/my-practice/client-service',
         'components/my-practice/custom-fields',
      ]
    },
      'components/super-mode',
  ]
};

export default sidebars;
